spring:
  profiles:
    active: local
  servlet:
    multipart:
      enabled: true
      max-file-size: 100MB
      max-request-size: 100MB

---
server:
  port: 8080
  tomcat:
    accesslog:
      pattern: "%{yyyy-MM-dd HH:mm:ss}t\t%s\t%r\t%{User-Agent}i\t%{Referer}i\t%a\t%b"
      enabled: true
    basedir: .

spring:
  profiles: local
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://172.23.16.23:3306/mobilepark?autoReconnect=true&useSSL=false&serverTimezone=UTC
    username: root
    password: root123
  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    open-in-view: false
    show-sql: true
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
  messages:
    #basename: classpath:/messages/messages
    basename: messages/messages
    encoding: UTF-8

logging:
  file: /Users/kas0610/Project/logs/airtalk.log
  level:
    root: INFO
    org.springframework.web: INFO
    org.hibernate: INFO
