spring:
  profiles:
    active: local
  servlet:
    multipart:
      enabled: true
      max-file-size: 100MB
      max-request-size: 100MB

---
server:
  port: 8080
  tomcat:
    accesslog:
      pattern: "%{yyyy-MM-dd HH:mm:ss}t\t%s\t%r\t%{User-Agent}i\t%{Referer}i\t%a\t%b"
      enabled: true
    basedir: .

spring:
  servlet:
    multipart:
      location: /Users/atingle/vscode_workspace/upload
      max-file-size: 100MB
      max-request-size: 100MB
  main:
    allow-bean-definition-overriding: true
  devtools:
    livereload:
      enabled: true
  profiles: local
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    # url: jdbc:mysql://172.23.16.23:3306/airtalk?autoReconnect=true&useSSL=false&serverTimezone=Asia/Seoul
    url: jdbc:mysql://3.34.5.49:3306/airtalk?autoReconnect=true&useSSL=false&serverTimezone=Asia/Seoul
    username: root
    password: Root.123
  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    open-in-view: false
    show-sql: true
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
  messages:
    #basename: classpath:/messages/messages
    basename: messages/messages
    encoding: UTF-8
  jwt:
    token:
      secret-key: AiraTalkVueBootstrapDashboardSpringbootSequrityJsonWebTokenSecretKeyProvider

logging:
  file: /Users/kas0610/Project/logs/airtalk.log
  level:
    root: INFO
    org.springframework.web: INFO
    org.hibernate: INFO

